name             'mysql-windows2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql'
long_description 'Installs/Configures mysql'
version '1.20170527.6'
