name 'win-installations'
maintainer 'Md Inzamamul aque'
maintainer_email 'mihaque313@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures win-installations'
long_description 'Installs/Configures win-installations'
version '0.1.2'
chef_version '>= 13.0'
